#!/bin/bash

echo "enter the salary"
read sal

if [ $sal -lt 10000 ]
then
echo "no tax"
elif [ $sal -gt 10000 -a $sal -lt 25000 ]
then
a=$(($sal*5/100))
echo "$a"
elif [ $sal -gt 25000 ]
then
b=$(($sal*10/100))
echo "$b"
else
echo "enter valid salary"
fi
