#!/bin/bash

echo "enter the vowels"
read v

if [ $v == A -o $v == a ]
then
echo "vowel"
elif [ $v == E -o $v == e ]
then
echo "vowel"
elif [ $v == O -o $v == o ]
then
echo "vowel"
elif [ $v == I -o $v == i ]
then
echo "vowel"
elif [ $v == U -o $v == u ]
then
echo "vowel"
else
echo "it is not vowel"
fi
