#!/bin/bash

echo "enter the days"
read day
case $day in
monday)echo "day in week"
;;
tuesday)echo "day in week"
;;
wednesday)echo "day in week"
;;
thursday)echo "day in week"
;;
friday)echo "day in week"
;;
sunday)echo "day in week"
;;
saturady)echo "day in week"
;;
*)echo "enter valid day"
;;
esac 
